In [ ]:
# workflow of ML --->
# Data Ingestion ----> Data cleaning and preprocessing ---> select ML Model ---->
# Model Training ----> Model Prediction -----> calculate Performance of Model.

In [ ]:
# data Cleaning and Preprocessing ----->
# Data -----> x_train,x_test , y_train, y_test
# Machine (x_train , y_tain)
# 1+1 =2
# 2+2 =4
# 3+2 = 5


# Machine(5+7) -----???? ----prediction =13
# 5+7 ---- x_test
# 12  ---- y_test
# 13  ---- y_pred
# Machine (y_pred , y_test) -----relation

In [ ]:
# how can we create data dividation ????

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df["fever"] = df["fever"].fillna(df["fever"].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
x = df.drop(columns =["has_covid"])      ####  Input or Independent Data
x.shape

(100, 5)

In [ ]:
y = df["has_covid"]      ###  target or dependent data
y.shape

(100,)

In [ ]:
# It is a function used to divide data into training and testing sets
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,
                                                       y,
                                                       test_size = 0.2,
                                                       random_state= 42)

In [ ]:
print("total data shape :",df.shape)
print("-------------------------------------")
print("Input data shape :",x.shape)
print("x_train data shape :",x_train.shape)
print("x_test data shape",x_test.shape)
print("-------------------------------------")
print("traget data shape :",y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape",y_test.shape)
print("--------------------------------------")

total data shape : (100, 6)
-------------------------------------
Input data shape : (100, 5)
x_train data shape : (80, 5)
x_test data shape (20, 5)
-------------------------------------
traget data shape : (100,)
y_train data shape : (80,)
y_test data shape (20,)
--------------------------------------

In [ ]:
df2 = pd.read_excel("/content/Customer_Call.xlsx")
df2.head(3)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True

In [ ]:
df2.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            1
Phone_Number         2
Address              0
Paying Customer      0
Do_Not_Contact       4
Not_Useful_Column    0
dtype: int64

In [ ]:
df2 = df2.dropna()

In [ ]:
df2.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            0
Phone_Number         0
Address              0
Paying Customer      0
Do_Not_Contact       0
Not_Useful_Column    0
dtype: int64

In [ ]:
x = df2.drop(columns = ["Paying Customer"])
x

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,Yes,False
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,True
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,No,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",No,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",No,False
18,1019,Creed,Braton,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",N,True

In [ ]:
y = df2["Paying Customer"]
y

0     Yes
1      No
3     Yes
4       Y
5     Yes
7       N
9     Yes
12    Yes
13    Yes
14      N
15     No
16    Yes
18    N/a
19    Yes
20    Yes
Name: Paying Customer, dtype: object

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,
                                                       y,
                                                       test_size =0.2,
                                                       random_state= 1)

In [ ]:
print("total data shape :",df2.shape)
print("-------------------------------------")
print("Input data shape :",x.shape)
print("x_train data shape :",x_train.shape)
print("x_test data shape",x_test.shape)
print("-------------------------------------")
print("traget data shape :",y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape",y_test.shape)
print("--------------------------------------")

total data shape : (15, 8)
-------------------------------------
Input data shape : (15, 7)
x_train data shape : (12, 7)
x_test data shape (3, 7)
-------------------------------------
traget data shape : (15,)
y_train data shape : (12,)
y_test data shape (3,)
--------------------------------------

In [ ]:
df3 = pd.read_csv("/content/titanic.csv")
df3.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q

In [ ]:
df3.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df3['Age'] = df3["Age"].fillna(df3["Age"].mean())

In [ ]:
df3['Fare'] = df3['Fare'].fillna(df3["Fare"].mean())

In [ ]:
df3["Cabin"].value_counts()

Cabin
B57 B59 B63 B66    3
B45                2
C23 C25 C27        2
C78                2
C31                2
                  ..
B41                1
C7                 1
D40                1
D38                1
C105               1
Name: count, Length: 76, dtype: int64

In [ ]:
df3["Cabin"] = df3["Cabin"].fillna("B57 B59 B63 B66")

In [ ]:
df3.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
x = df3.drop(columns =["Survived"])
x.shape

(418, 11)

In [ ]:
y = df3["Survived"]
y.shape

(418,)

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,
                                                       y,
                                                       test_size =0.2,
                                                       random_state= 1)

In [ ]:
print("total data shape :",df3.shape)
print("-------------------------------------")
print("Input data shape :",x.shape)
print("x_train data shape :",x_train.shape)
print("x_test data shape",x_test.shape)
print("-------------------------------------")
print("traget data shape :",y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape",y_test.shape)
print("--------------------------------------")

total data shape : (418, 12)
-------------------------------------
Input data shape : (418, 11)
x_train data shape : (334, 11)
x_test data shape (84, 11)
-------------------------------------
traget data shape : (418,)
y_train data shape : (334,)
y_test data shape (84,)
--------------------------------------

In [ ]:
# Normal distribution ------>
# from central tendency(mean , median , mode) ---->equal distribution of data points on both sides of the center
# helps in standardization (removing mean and scaling to unit variance)----> same difference b/w two data points
# Identification
# mean = 0 , standard deviation = 1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop(columns =["city","cough"])

In [ ]:
df.head()

   age  gender  fever has_covid
0   60    Male  103.0        No
1   27    Male  100.0       Yes
2   42    Male  101.0        No
3   31  Female   98.0        No
4   65  Female  101.0        No

In [ ]:
df["has_covid"] = df['has_covid'].map({"Yes":1,"No":0})
df['gender'] = df["gender"].map({"Female":1,"Male":0})

In [ ]:
df.head()

   age  gender  fever  has_covid
0   60       0  103.0          0
1   27       0  100.0          1
2   42       0  101.0          0
3   31       1   98.0          0
4   65       1  101.0          0

In [ ]:
x = df.drop(columns =["has_covid"])
y = df["has_covid"]

In [ ]:
# that splits your dataset into training and testing subsets
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42)

In [ ]:
np.round(x_train.describe() , 2)

         age  gender   fever
count  72.00   72.00   72.00
mean   43.53    0.64  100.74
std    25.30    0.48    2.12
min     5.00    0.00   98.00
25%    19.75    0.00   99.00
50%    47.00    1.00  101.00
75%    65.25    1.00  102.25
max    83.00    1.00  104.00

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
# fit means learn from the parameters and transfrom means apply on that data
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [ ]:
np.round(x_train_new.describe() , 2)

         age  gender  fever
count  72.00   72.00  72.00
mean   -0.00    0.00  -0.00
std     1.01    1.01   1.01
min    -1.53   -1.33  -1.30
25%    -0.95   -1.33  -0.83
50%     0.14    0.75   0.13
75%     0.86    0.75   0.72
max     1.57    0.75   1.55

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df = df.drop(columns =["day"])

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
df['sex'] = df['sex'].map({"Male":0,"Female":1})
df['smoker'] = df['smoker'].map({"Yes":1,"No":0})
df['time'] = df['time'].map({"Dinner":1,"Lunch":0})

In [ ]:
np.round(df.describe(),2)

       total_bill     tip    size
count      244.00  244.00  244.00
mean        19.79    3.00    2.57
std          8.90    1.38    0.95
min          3.07    1.00    1.00
25%         13.35    2.00    2.00
50%         17.80    2.90    2.00
75%         24.13    3.56    3.00
max         50.81   10.00    6.00

In [ ]:
df.head(3)

   total_bill   tip sex smoker time  size
0       16.99  1.01   1      0    1     2
1       10.34  1.66   0      0    1     3
2       21.01  3.50   0      0    1     3

In [ ]:
x = df.drop(columns =['total_bill'])
y = df['total_bill']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size =0.2,random_state=1)

In [ ]:
np.round(x_train.describe() , 2)

          tip    size
count  195.00  195.00
mean     2.93    2.56
std      1.31    0.98
min      1.00    1.00
25%      2.00    2.00
50%      2.75    2.00
75%      3.50    3.00
max      9.00    6.00

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_2 = pd.DataFrame(x_train_sc, columns = x_train.columns)

In [ ]:
np.round(x_train_2.describe(),2)

            0       1       2       3       4
count  195.00  195.00  195.00  195.00  195.00
mean     0.00    0.00   -0.00   -0.00   -0.00
std      1.00    1.00    1.00    1.00    1.00
min     -1.48   -0.72   -0.74   -1.56   -1.60
25%     -0.72   -0.72   -0.74   -1.56   -0.58
50%     -0.14   -0.72   -0.74    0.64   -0.58
75%      0.43    1.40    1.35    0.64    0.45
max      4.65    1.40    1.35    0.64    3.52