In [ ]:
# NORMALIZATION -------> Min  = 0 , Max = 1
# scaling them into a specific range from 0 to 1 where min = 0 and max = 1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/Churn_Modelling.csv")
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [ ]:
df = df.drop(columns = ['Surname','Geography','Gender'])

In [ ]:
df.head(3)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
CreditScore        0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
x = df.drop(columns = ['Exited'])
y = df['Exited']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size = 0.2 , random_state = 1)

In [ ]:
np.round(x_train.describe(),2)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,5018.44,15691212.34,650.31,38.89,5.03,76463.44,1.53,0.71,0.51,100143.43
std,2885.30,71638.16,96.68,10.47,2.89,62372.54,0.58,0.46,0.50,57574.88
min,1.00,15565701.00,350.00,18.00,0.00,0.00,1.00,0.00,0.00,91.75
25%,2532.75,15629088.25,583.00,32.00,3.00,0.00,1.00,0.00,0.00,51014.84
50%,5026.50,15691713.00,651.00,37.00,5.00,97055.14,1.00,1.00,1.00,99836.22
75%,7518.50,15753104.00,718.00,44.00,7.00,127639.37,2.00,1.00,1.00,149373.53
max,10000.00,15815690.00,850.00,92.00,10.00,250898.09,4.00,1.00,1.00,199970.74

#Apply Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_new = pd.DataFrame(x_train_mn, columns = x_train.columns)

In [ ]:
np.round(x_new.describe(),2)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.50,0.50,0.60,0.28,0.50,0.30,0.18,0.71,0.51,0.50
std,0.29,0.29,0.19,0.14,0.29,0.25,0.19,0.46,0.50,0.29
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.25,0.47,0.19,0.30,0.00,0.00,0.00,0.00,0.25
50%,0.50,0.50,0.60,0.26,0.50,0.39,0.00,1.00,1.00,0.50
75%,0.75,0.75,0.74,0.35,0.70,0.51,0.33,1.00,1.00,0.75
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [ ]:
df2 = pd.read_csv("/content/toyota.csv")
df2

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,GT86,2016,16000,Manual,24089,Petrol,265,36.2,2.0
1,GT86,2017,15995,Manual,18615,Petrol,145,36.2,2.0
2,GT86,2015,13998,Manual,27469,Petrol,265,36.2,2.0
3,GT86,2017,18998,Manual,14736,Petrol,150,36.2,2.0
4,GT86,2017,17498,Manual,36284,Petrol,145,36.2,2.0
...,...,...,...,...,...,...,...,...,...
6733,IQ,2011,5500,Automatic,30000,Petrol,20,58.9,1.0
6734,Urban Cruiser,2011,4985,Manual,36154,Petrol,125,50.4,1.3
6735,Urban Cruiser,2012,4995,Manual,46000,Diesel,125,57.6,1.4
6736,Urban Cruiser,2011,3995,Manual,60700,Petrol,125,50.4,1.3
6737,Urban Cruiser,2011,4495,Manual,45128,Petrol,125,50.4,1.3

In [ ]:
df2 = df2.drop(columns = ['model','year'])

In [ ]:
df2['transmission'].value_counts()

transmission
Manual       3826
Automatic    2657
Semi-Auto     254
Other           1
Name: count, dtype: int64

In [ ]:
df2['fuelType'] = df2['fuelType'].map({'Petrol':0,'Hybrid':1,'Diesel':2,'Other':3})
df2['transmission'] = df2['transmission'].map({'Manual':0,'Automatic':1,'Semi-Auto':2,'Other':3})

In [ ]:
df2.head()

   price  transmission  mileage  fuelType  tax   mpg  engineSize
0  16000             0    24089         0  265  36.2         2.0
1  15995             0    18615         0  145  36.2         2.0
2  13998             0    27469         0  265  36.2         2.0
3  18998             0    14736         0  150  36.2         2.0
4  17498             0    36284         0  145  36.2         2.0

In [ ]:
x = df2.drop(columns = ['price'])
y = df2['price']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2, random_state = 1)

In [ ]:
np.round(x_train.describe(),2)

       transmission    mileage  fuelType      tax      mpg  engineSize
count       5390.00    5390.00   5390.00  5390.00  5390.00     5390.00
mean           0.47   22771.10      0.51    94.51    63.11        1.47
std            0.57   19077.77      0.71    74.36    16.46        0.44
min            0.00       2.00      0.00     0.00     2.80        0.00
25%            0.00    9326.25      0.00     0.00    55.40        1.00
50%            0.00   18399.50      0.00   135.00    61.40        1.50
75%            1.00   31057.00      1.00   145.00    70.60        1.80
max            3.00  174419.00      3.00   565.00   235.00        4.50

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_new2 = pd.DataFrame(x_train_mn, columns = x_train.columns)

In [ ]:
np.round(x_new2.describe(),2)

       transmission  mileage  fuelType      tax      mpg  engineSize
count       5390.00  5390.00   5390.00  5390.00  5390.00     5390.00
mean           0.16     0.13      0.17     0.17     0.26        0.33
std            0.19     0.11      0.24     0.13     0.07        0.10
min            0.00     0.00      0.00     0.00     0.00        0.00
25%            0.00     0.05      0.00     0.00     0.23        0.22
50%            0.00     0.11      0.00     0.24     0.25        0.33
75%            0.33     0.18      0.33     0.26     0.29        0.40
max            1.00     1.00      1.00     1.00     1.00        1.00

In [ ]:
df3 = pd.read_csv("/content/covid_toy.csv")
df3.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df3['fever'] = df3['fever'].fillna(df3['fever'].mean())

In [ ]:
df3.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df3 = df3.drop(columns = ['city'])

In [ ]:
df3.head(3)

   age gender  fever cough has_covid
0   60   Male  103.0  Mild        No
1   27   Male  100.0  Mild       Yes
2   42   Male  101.0  Mild        No

In [ ]:
df3['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [ ]:
df3['gender'] = df3['gender'].map({'Male':0,'Female':1})
df3['cough'] = df3['cough'].map({'Mild':0,'Strong':1})
df3['has_covid'] = df3['has_covid'].map({'No':0,'Yes':1})

In [ ]:
df3.head(3)

   age  gender  fever  cough  has_covid
0   60       0  103.0      0          0
1   27       0  100.0      0          1
2   42       0  101.0      0          0

In [ ]:
x = df3.drop(columns = ['has_covid'])
y = df3['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size= 0.2,random_state = 1)

In [ ]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   80.00  80.00
mean   43.66    0.57  100.95   0.38
std    24.96    0.50    2.00   0.49
min     5.00    0.00   98.00   0.00
25%    19.75    0.00   99.00   0.00
50%    45.00    1.00  101.00   0.00
75%    65.00    1.00  102.25   1.00
max    84.00    1.00  104.00   1.00

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_mn = mn.fit_transform(x_train)

In [ ]:
x_new = pd.DataFrame(x_mn , columns = x_train.columns)

In [ ]:
np.round(x_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean    0.49    0.57   0.49   0.38
std     0.32    0.50   0.33   0.49
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.17   0.00
50%     0.51    1.00   0.50   0.00
75%     0.76    1.00   0.71   1.00
max     1.00    1.00   1.00   1.00

In [ ]:
import seaborn as sns

In [ ]:
df= sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df = df.drop(columns = ['time','day'])

In [ ]:
df.head(2)

   total_bill   tip     sex smoker  size
0       16.99  1.01  Female     No     2
1       10.34  1.66    Male     No     3

In [ ]:
df['sex'] = df['sex'].map({'Male':0,'Feamle':1})
df['smoker'] = df['smoker'].map({'No':0,'Yes':1})

In [ ]:
x = df.drop(columns = ['total_bill'])

In [ ]:
y = df['total_bill']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2,random_state=1)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_mn = mn.fit_transform(x_train)

In [ ]:
x_new = pd.DataFrame(x_mn,columns = x_train.columns)

In [ ]:
np.round(x_new.describe(),2)

          tip    sex  smoker    size
count  195.00  129.0  195.00  195.00
mean     0.24    0.0    0.35    0.31
std      0.16    0.0    0.48    0.20
min      0.00    0.0    0.00    0.00
25%      0.12    0.0    0.00    0.20
50%      0.22    0.0    0.00    0.20
75%      0.31    0.0    1.00    0.40
max      1.00    0.0    1.00    1.00