In [ ]:
# ML Model
# (1). Supervised ML Models ---> In this , we will trained our labelled Data
# (a). Descrete ----> LogisticRegression , Decisiontreeclassifier , Randomforestclassifer , naive bayes .
# (b). Continuous ---> LinearRgression , D.T. Regressor , R.F Regressor

# (2).Unsupervised ML Models ----> In this , we will trained our unlabelled data .
# KMeans , PCA , Apriori

In [ ]:
# (1). Supervised ML Model
# (1). LinearRegression

In [ ]:
# workFlow --->
# DataIngestion -----> Data Cleaning and Preprocessing ----> select ML based on target column
# ------> Model Training -----> Model Prediction ----> Model Evalution

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
x = df.drop(columns = ['charges'])
y = df['charges']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
x['sex'] = lb.fit_transform(x['sex'])
x['smoker'] = lb.fit_transform(x['smoker'])
x['region'] = lb.fit_transform(x['region'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train ,y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42 )

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(x_train , y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test , y_pred)

0.7833463107364539

In [ ]:
c = pd.read_csv("/content/Churn_Modelling.csv")
c.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
c = c.drop(columns = ['Surname'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
x = c.drop(columns = ['EstimatedSalary'])
y = c['EstimatedSalary']

In [ ]:
lb = LabelEncoder()

In [ ]:
x.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,0

In [ ]:
x['Geography'] = lb.fit_transform(x['Geography'])
x['Gender'] = lb.fit_transform(x['Gender'])

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42 )

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(x_train , y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test , y_pred)

-0.0038845997234846497

#RIDGE AND LASSO

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
x= df.drop(columns = ['charges'])

In [ ]:
y = df['charges']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
x['sex'] = lb.fit_transform(x['sex'])
x['smoker'] = lb.fit_transform(x['smoker'])
x['region'] = lb.fit_transform(x['region'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split (x , y , test_size = 0.2 , random_state = 42)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr .fit(x_train , y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test,y_pred )

0.7833463107364539

In [ ]:
from sklearn.linear_model import Ridge , Lasso

In [ ]:
# Ridge Regression Model
ridgeReg = Ridge(alpha = 10)

ridgeReg.fit(x_train , y_train)

Ridge(alpha=10)

In [ ]:
# train and test scorefor ridge regression
train_score_ridge = ridgeReg.score(x_train , y_train)
test_score_ridge = ridgeReg.score(x_test , y_test)

print("the train score for ridge model is {}".format(train_score_ridge))
print("the test score for ridge model is {}".format(test_score_ridge))

the train score for ridge model is 0.7398386827259329
the test score for ridge model is 0.7793155691007558

#Lasso

In [ ]:
lasso = Lasso(alpha = 10)
lasso.fit(x_train,y_train)
train_score_ls = lasso.score(x_train , y_train)
test_score_ls = lasso.score(x_test , y_test)

print("the train score for ls model is{}".format(train_score_ls))
print('the test score for ls model is{}'.format(test_score_ls))

the train score for ls model is0.7416990458357842
the test score for ls model is0.7831229831162652

#polynomail Regression

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly = PolynomialFeatures(degree = 4)
x_poly = poly.fit_transform(x_train)

poly.fit(x_poly , y_train)

PolynomialFeatures(degree=4)

In [ ]:
lin2 = LinearRegression()
lin2.fit(x_poly , y_train)

LinearRegression()

In [ ]:
y_pred = lin2.predict(poly.fit_transform(x_test))

In [ ]:
r2_score(y_test ,y_pred)

0.7717529958521865

In [ ]:
# data ----> x,y
# x ----> binomail feature show in visualization
# x -----> polynomial regression
# y -----> no change
# linear_regression.fit(x_poly , y)
# y_pred
# r2_score(y_test , y_pred)